import { EAPackage, PackageId } from './types';

export const EA_PACKAGES: EAPackage[] = [
  // BASIC TIER
  {
    id: 'basic-xauusd' as any,
    name: 'Gold Master Basic (XAUUSD)',
    category: 'GOLD',
    tradingAssets: 'Basic',
    price: 5000,
    capitalRange: 'ทุน 100$ - 500$',
    description: 'ระบบ AI พื้นฐานสำหรับการเทรดทองคำ (XAUUSD) เหมาะสำหรับมือใหม่',
    userCount: 1250,
    performanceSummary: 'Win Rate 68% | Daily Active: 450',
    status: 'active',
    stats: { dailyWinRate: '65%', weeklyWinRate: '66%', monthlyWinRate: '68%', globalRank: 10, totalActiveUsers: 1250, dailyActiveUsers: 450, weeklyActiveUsers: 850 },
    features: ['รองรับ 1 บัญชีเทรด', 'ระบบบริหารความเสี่ยงพื้นฐาน'],
    reviews: [],
    supportedSymbols: ['XAUUSD']
  },
  {
    id: 'basic-eurusd' as any,
    name: 'Forex Flow Basic (EURUSD)',
    category: 'FOREX',
    tradingAssets: 'Basic',
    price: 5000,
    capitalRange: 'ทุน 100$ - 500$',
    description: 'ระบบเทรดคู่เงิน EURUSD อัตโนมัติ เน้นความปลอดภัยสูง',
    userCount: 980,
    performanceSummary: 'Win Rate 64% | Daily Active: 320',
    status: 'active',
    stats: { dailyWinRate: '62%', weeklyWinRate: '63%', monthlyWinRate: '64%', globalRank: 15, totalActiveUsers: 980, dailyActiveUsers: 320, weeklyActiveUsers: 580 },
    features: ['รองรับ 1 บัญชีเทรด', 'กลยุทธ์ Trend Following'],
    reviews: [],
    supportedSymbols: ['EURUSD']
  },
  {
    id: 'basic-cl-oil' as any,
    name: 'Oil Trader Basic (CL-OIL)',
    category: 'OIL',
    tradingAssets: 'Basic',
    price: 5000,
    capitalRange: 'ทุน 200$ - 500$',
    description: 'ระบบเทรดน้ำมัน (WTI/CL-OIL) สำหรับผู้เริ่มต้น',
    userCount: 650,
    performanceSummary: 'Win Rate 62% | Daily Active: 180',
    status: 'active',
    stats: { dailyWinRate: '60%', weeklyWinRate: '61%', monthlyWinRate: '62%', globalRank: 22, totalActiveUsers: 650, dailyActiveUsers: 180, weeklyActiveUsers: 340 },
    features: ['รองรับ 1 บัญชีเทรด', 'Volatility Protection'],
    reviews: [],
    supportedSymbols: ['CL-OIL']
  },
  {
    id: 'basic-xagusd' as any,
    name: 'Silver Starter Basic (XAGUSD)',
    category: 'SILVER',
    tradingAssets: 'Basic',
    price: 5000,
    capitalRange: 'ทุน 100$ - 500$',
    description: 'ระบบเทรดโลหะเงินอัจฉริยะสำหรับมือใหม่ เน้นการเรียนรู้ตลาด',
    userCount: 420,
    performanceSummary: 'Win Rate 61% | Daily Active: 120',
    status: 'active',
    stats: { dailyWinRate: '59%', weeklyWinRate: '60%', monthlyWinRate: '61%', globalRank: 25, totalActiveUsers: 420, dailyActiveUsers: 120, weeklyActiveUsers: 240 },
    features: ['รองรับ 1 บัญชีเทรด', 'Basic News Filter'],
    reviews: [],
    supportedSymbols: ['XAGUSD']
  },

  // STANDARD TIER
  {
    id: 'standard-xauaud' as any,
    name: 'Gold Scalper Plus (XAUAUD)',
    category: 'GOLD',
    tradingAssets: 'Standard',
    price: 10000,
    capitalRange: 'ทุน 500$ - 2,000$',
    description: 'ระบบ Scalping ทองคำ (XAUAUD) ความถี่สูง พร้อม Trailing Stop',
    userCount: 2200,
    performanceSummary: 'Win Rate 72% | Daily Active: 840',
    status: 'active',
    stats: { dailyWinRate: '70%', weeklyWinRate: '71%', monthlyWinRate: '72%', globalRank: 2, totalActiveUsers: 2200, dailyActiveUsers: 840, weeklyActiveUsers: 1450 },
    features: ['รองรับ 2 บัญชีเทรด', 'Multi-layer Trailing'],
    reviews: [],
    supportedSymbols: ['XAUAUD']
  },
  {
    id: 'standard-gbpusd' as any,
    name: 'Pound Power Standard (GBPUSD)',
    category: 'FOREX',
    tradingAssets: 'Standard',
    price: 10000,
    capitalRange: 'ทุน 500$ - 1,500$',
    description: 'ระบบเทรดคู่เงิน GBPUSD ที่มีความผันผวนสูง ให้ผลตอบแทนคุ้มค่า',
    userCount: 1800,
    performanceSummary: 'Win Rate 70% | Daily Active: 620',
    status: 'active',
    stats: { dailyWinRate: '68%', weeklyWinRate: '69%', monthlyWinRate: '70%', globalRank: 8, totalActiveUsers: 1800, dailyActiveUsers: 620, weeklyActiveUsers: 1100 },
    features: ['รองรับ 2 บัญชีเทรด', 'Volatility Shield'],
    reviews: [],
    supportedSymbols: ['GBPUSD']
  },
  {
    id: 'standard-xagusd' as any,
    name: 'Silver Pro Standard (XAGUSD)',
    category: 'SILVER',
    tradingAssets: 'Standard',
    price: 10000,
    capitalRange: 'ทุน 500$ - 2,500$',
    description: 'ระบบเทรดโลหะเงิน (XAGUSD) อัตโนมัติ เน้นกำไรสะสมแบบมั่นคง',
    userCount: 1450,
    performanceSummary: 'Win Rate 71% | Daily Active: 480',
    status: 'active',
    stats: { dailyWinRate: '69%', weeklyWinRate: '70%', monthlyWinRate: '71%', globalRank: 12, totalActiveUsers: 1450, dailyActiveUsers: 480, weeklyActiveUsers: 820 },
    features: ['รองรับ 2 บัญชีเทรด', 'News Filter System'],
    reviews: [],
    supportedSymbols: ['XAGUSD']
  },
  {
    id: 'standard-ukoousd' as any,
    name: 'Brent Oil Standard (UKOUSD)',
    category: 'OIL',
    tradingAssets: 'Standard',
    price: 10000,
    capitalRange: 'ทุน 500$ - 3,000$',
    description: 'ระบบเทรดน้ำมันดิบ Brent เน้นรอบการวิ่งของราคาที่ชัดเจน',
    userCount: 880,
    performanceSummary: 'Win Rate 69% | Daily Active: 240',
    status: 'active',
    stats: { dailyWinRate: '67%', weeklyWinRate: '68%', monthlyWinRate: '69%', globalRank: 20, totalActiveUsers: 880, dailyActiveUsers: 240, weeklyActiveUsers: 480 },
    features: ['รองรับ 2 บัญชีเทรด', 'Trend Analysis Engine'],
    reviews: [],
    supportedSymbols: ['UKOUSD']
  },

  // PRO TIER
  {
    id: 'pro-xaueur' as any,
    name: 'Gold Institutional Pro (XAUEUR)',
    category: 'GOLD',
    tradingAssets: 'Pro',
    price: 15000,
    capitalRange: 'ทุน 1,000$ - 5,000$',
    description: 'วิเคราะห์ทองคำ (XAUEUR) เชิงลึกข้ามตลาด เพื่อผลตอบแทนระดับมืออาชีพ',
    userCount: 3850,
    performanceSummary: 'Win Rate 78% | Daily Active: 1,450',
    status: 'active',
    stats: { dailyWinRate: '76%', weeklyWinRate: '77%', monthlyWinRate: '78%', globalRank: 1, totalActiveUsers: 3850, dailyActiveUsers: 1450, weeklyActiveUsers: 2400 },
    features: ['ไม่จำกัดบัญชีเทรด', 'Dedicated Support 24/5'],
    reviews: [],
    supportedSymbols: ['XAUEUR']
  },
  {
    id: 'pro-usdjpy' as any,
    name: 'Yen Master Pro (USDJPY)',
    category: 'FOREX',
    tradingAssets: 'Pro',
    price: 15000,
    capitalRange: 'ทุน 1,000$ - 7,000$',
    description: 'ระบบเทรด USDJPY อัจฉริยะ พร้อม Hedging ขั้นสูงเพื่อรับมือความผันผวน',
    userCount: 2200,
    performanceSummary: 'Win Rate 75% | Daily Active: 740',
    status: 'active',
    stats: { dailyWinRate: '73%', weeklyWinRate: '74%', monthlyWinRate: '75%', globalRank: 7, totalActiveUsers: 2200, dailyActiveUsers: 740, weeklyActiveUsers: 1450 },
    features: ['ไม่จำกัดบัญชีเทรด', 'Account Manager'],
    reviews: [],
    supportedSymbols: ['USDJPY']
  },
  {
    id: 'pro-usousd' as any,
    name: 'Energy Elite Pro (USOUSD)',
    category: 'OIL',
    tradingAssets: 'Pro',
    price: 15000,
    capitalRange: 'ทุน 2,000$ - 10,000$',
    description: 'ที่สุดของระบบเทรดพลังงาน (USOUSD) สำหรับพอร์ตขนาดใหญ่',
    userCount: 1200,
    performanceSummary: 'Win Rate 77% | Daily Active: 450',
    status: 'active',
    stats: { dailyWinRate: '75%', weeklyWinRate: '76%', monthlyWinRate: '77%', globalRank: 19, totalActiveUsers: 1200, dailyActiveUsers: 450, weeklyActiveUsers: 850 },
    features: ['ไม่จำกัดบัญชีเทรด', 'High-Speed Execution'],
    reviews: [],
    supportedSymbols: ['USOUSD']
  },
  {
    id: 'pro-xagaud' as any,
    name: 'Silver Elite Pro (XAGAUD)',
    category: 'SILVER',
    tradingAssets: 'Pro',
    price: 15000,
    capitalRange: 'ทุน 1,000$ - 5,000$',
    description: 'ระบบเทรดโลหะเงิน (XAGAUD) ขั้นสูง วิเคราะห์ความสัมพันธ์ของคู่เงิน AUD',
    userCount: 650,
    performanceSummary: 'Win Rate 74% | Daily Active: 180',
    status: 'active',
    stats: { dailyWinRate: '72%', weeklyWinRate: '73%', monthlyWinRate: '74%', globalRank: 21, totalActiveUsers: 650, dailyActiveUsers: 180, weeklyActiveUsers: 360 },
    features: ['ไม่จำกัดบัญชีเทรด', 'Correlation Matrix AI'],
    reviews: [],
    supportedSymbols: ['XAGAUD']
  },

  // VIP TIER
  {
    id: 'vip-xaujpy' as any,
    name: 'Gold Hedge VIP (XAUJPY)',
    category: 'GOLD',
    tradingAssets: 'VIP',
    price: 20000,
    capitalRange: 'ทุน 3,000$ - 15,000$',
    description: 'ระบบ Hedging อัจฉริยะสำหรับทองคำ (XAUJPY) ป้องกันความเสี่ยงข่าวแรงระดับโลก',
    userCount: 1650,
    performanceSummary: 'Win Rate 82% | Daily Active: 580',
    status: 'active',
    stats: { dailyWinRate: '80%', weeklyWinRate: '81%', monthlyWinRate: '82%', globalRank: 6, totalActiveUsers: 1650, dailyActiveUsers: 580, weeklyActiveUsers: 1100 },
    features: ['Advanced Hedging Logic', 'Custom Risk Profile'],
    reviews: [],
    supportedSymbols: ['XAUJPY']
  },
  {
    id: 'vip-xagaud' as any,
    name: 'Silver Shield VIP (XAGAUD)',
    category: 'SILVER',
    tradingAssets: 'VIP',
    price: 20000,
    capitalRange: 'ทุน 5,000$ - 20,000$',
    description: 'การจัดการความเสี่ยงระดับสูงสำหรับโลหะเงิน (XAGAUD) แม่นยำทุกสภาวะตลาด',
    userCount: 950,
    performanceSummary: 'Win Rate 79% | Daily Active: 320',
    status: 'active',
    stats: { dailyWinRate: '77%', weeklyWinRate: '78%', monthlyWinRate: '79%', globalRank: 11, totalActiveUsers: 950, dailyActiveUsers: 320, weeklyActiveUsers: 650 },
    features: ['VIP Signal Group', 'Direct Developer Access'],
    reviews: [],
    supportedSymbols: ['XAGAUD']
  },
  {
    id: 'vip-usdcad' as any,
    name: 'Loonie Legend VIP (USDCAD)',
    category: 'FOREX',
    tradingAssets: 'VIP',
    price: 20000,
    capitalRange: 'ทุน 3,000$ - 10,000$',
    description: 'ระบบเทรด USDCAD ขั้นสูง พร้อมวิเคราะห์สเปรดและค่าธรรมเนียมแบบเรียลไทม์',
    userCount: 1100,
    performanceSummary: 'Win Rate 81% | Daily Active: 410',
    status: 'active',
    stats: { dailyWinRate: '79%', weeklyWinRate: '80%', monthlyWinRate: '81%', globalRank: 16, totalActiveUsers: 1100, dailyActiveUsers: 410, weeklyActiveUsers: 780 },
    features: ['Portfolio Rebalancing', 'Multi-Broker Optimization'],
    reviews: [],
    supportedSymbols: ['USDCAD']
  },
  {
    id: 'vip-ukoousdft' as any,
    name: 'Oil Futures VIP (UKOUSDft)',
    category: 'OIL',
    tradingAssets: 'VIP',
    price: 20000,
    capitalRange: 'ทุน 5,000$ - 30,000$',
    description: 'ระบบเทรดน้ำมันฟิวเจอร์สระดับ VIP พร้อมระบบจัดการความเสี่ยงทับซ้อน',
    userCount: 540,
    performanceSummary: 'Win Rate 80% | Daily Active: 180',
    status: 'active',
    stats: { dailyWinRate: '78%', weeklyWinRate: '79%', monthlyWinRate: '80%', globalRank: 23, totalActiveUsers: 540, dailyActiveUsers: 180, weeklyActiveUsers: 360 },
    features: ['Priority Account Management', 'VPS Hosting Included'],
    reviews: [],
    supportedSymbols: ['UKOUSDft']
  },

  // VVIP TIER
  {
    id: 'vvip-xauusd-institutional' as any,
    name: 'Gold Institutional VVIP (XAUUSD)',
    category: 'GOLD',
    tradingAssets: 'VVIP',
    price: 30000,
    capitalRange: 'ทุน 10,000$ - 100,000$',
    description: 'ระบบระดับกองทุนชั้นนำ วิเคราะห์ Institutional Flow สำหรับทองคำแบบวินาทีต่อวินาที',
    userCount: 680,
    performanceSummary: 'Win Rate 86% | Daily Active: 210',
    status: 'active',
    stats: { dailyWinRate: '84%', weeklyWinRate: '85%', monthlyWinRate: '86%', globalRank: 14, totalActiveUsers: 680, dailyActiveUsers: 210, weeklyActiveUsers: 480 },
    features: ['Personal Consultant', 'Private VPS 1 ปี'],
    reviews: [],
    supportedSymbols: ['XAUUSD']
  },
  {
    id: 'vvip-audusd' as any,
    name: 'Aussie Alpha VVIP (AUDUSD)',
    category: 'FOREX',
    tradingAssets: 'VVIP',
    price: 30000,
    capitalRange: 'ทุน 10,000$ - 50,000$',
    description: 'ที่สุดของ AUDUSD Trading มั่นคงและปลอดภัยสูงสุดด้วยอัลกอริทึมระดับโลก',
    userCount: 520,
    performanceSummary: 'Win Rate 84% | Daily Active: 180',
    status: 'active',
    stats: { dailyWinRate: '82%', weeklyWinRate: '83%', monthlyWinRate: '84%', globalRank: 18, totalActiveUsers: 520, dailyActiveUsers: 180, weeklyActiveUsers: 390 },
    features: ['Institutional Algorithm', 'VIP Concierge'],
    reviews: [],
    supportedSymbols: ['AUDUSD']
  },
  {
    id: 'vvip-ukoousd' as any,
    name: 'Brent Brent Oil VVIP (UKOUSD)',
    category: 'OIL',
    tradingAssets: 'VVIP',
    price: 30000,
    capitalRange: 'ทุน 15,000$ - 70,000$',
    description: 'ระบบเทรดน้ำมันดิบเบรนท์สำหรับนักลงทุนรายใหญ่ ปลอดภัยด้วยทุนสำรอง',
    userCount: 450,
    performanceSummary: 'Win Rate 85% | Daily Active: 150',
    status: 'active',
    stats: { dailyWinRate: '83%', weeklyWinRate: '84%', monthlyWinRate: '85%', globalRank: 20, totalActiveUsers: 450, dailyActiveUsers: 150, weeklyActiveUsers: 320 },
    features: ['Exclusive Private Access', 'Zero Latency VPS'],
    reviews: [],
    supportedSymbols: ['UKOUSD']
  },
  {
    id: 'vvip-xagaud' as any,
    name: 'Silver VVIP Institutional (XAGAUD)',
    category: 'SILVER',
    tradingAssets: 'VVIP',
    price: 30000,
    capitalRange: 'ทุน 10,000$ - 40,000$',
    description: 'เทคโนโลยีระดับสูงสำหรับตลาดโลหะเงิน (XAGAUD) พร้อมระบุโซนการกลับตัวแม่นยำ',
    userCount: 280,
    performanceSummary: 'Win Rate 83% | Daily Active: 90',
    status: 'active',
    stats: { dailyWinRate: '81%', weeklyWinRate: '82%', monthlyWinRate: '83%', globalRank: 24, totalActiveUsers: 280, dailyActiveUsers: 90, weeklyActiveUsers: 180 },
    features: ['Institutional Order Flow', 'Private Mentorship'],
    reviews: [],
    supportedSymbols: ['XAGAUD']
  },

  // VVVIP TIER
  {
    id: 'vvvip-xauusd-ultimate' as any,
    name: 'Ultimate Gold Vault VVVIP',
    category: 'GOLD',
    tradingAssets: 'VVVIP',
    price: 50000,
    capitalRange: 'ทุน 50,000$ ขึ้นไป',
    description: 'ขีดสุดของเทคโนโลยีการทำกำไรทองคำระดับโลก พร้อมการค้ำประกันความเสียหายเต็มวงเงิน',
    userCount: 820,
    performanceSummary: 'Win Rate 89% | Daily Active: 280',
    status: 'active',
    stats: { dailyWinRate: '87%', weeklyWinRate: '88%', monthlyWinRate: '89%', globalRank: 5, totalActiveUsers: 820, dailyActiveUsers: 280, weeklyActiveUsers: 540 },
    features: ['Capital Protection Program', 'Custom Strategy Builder'],
    reviews: [],
    supportedSymbols: ['XAUUSD', 'XAUAUD', 'XAUEUR', 'XAUJPY']
  },
  {
    id: 'vvvip-forex-multi' as any,
    name: 'Global Forex Institutional VVVIP',
    category: 'FOREX',
    tradingAssets: 'VVVIP',
    price: 50000,
    capitalRange: 'ทุน 100,000$ ขึ้นไป',
    description: 'ระบบเทรด 8 คู่เงินหลัก (EUR, GBP, JPY, CAD, AUD, GBX, CZK, AED) ในหนึ่งเดียว',
    userCount: 650,
    performanceSummary: 'Win Rate 90% | Daily Active: 210',
    status: 'active',
    stats: { dailyWinRate: '88%', weeklyWinRate: '89%', monthlyWinRate: '90%', globalRank: 13, totalActiveUsers: 650, dailyActiveUsers: 210, weeklyActiveUsers: 420 },
    features: ['Multi-Asset Arbitrage', 'Private Board Access'],
    reviews: [],
    supportedSymbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCAD', 'AUDUSD', 'GBXUSD', 'USDCZK', 'USDAED']
  },
  {
    id: 'vvvip-ukoousdft' as any,
    name: 'Oil Futures Institutional VVVIP (UKOUSDft)',
    category: 'OIL',
    tradingAssets: 'VVVIP',
    price: 50000,
    capitalRange: 'ทุน 100,000$ ขึ้นไป',
    description: 'ระบบเทรดน้ำมันฟิวเจอร์สระดับสถาบัน เติบโตอย่างไร้ขีดจำกัดด้วย HFT Logic',
    userCount: 340,
    performanceSummary: 'Win Rate 91% | Daily Active: 120',
    status: 'active',
    stats: { dailyWinRate: '89%', weeklyWinRate: '90%', monthlyWinRate: '91%', globalRank: 17, totalActiveUsers: 340, dailyActiveUsers: 120, weeklyActiveUsers: 240 },
    features: ['Direct Exchange Bridge', 'VVIP Account Manager'],
    reviews: [],
    supportedSymbols: ['CL-OIL', 'USOUSD', 'UKOUSD', 'UKOUSDft']
  },
  {
    id: 'vvvip-silver-ultimate' as any,
    name: 'Silver Sovereign Ultimate VVVIP',
    category: 'SILVER',
    tradingAssets: 'VVVIP',
    price: 50000,
    capitalRange: 'ทุน 50,000$ ขึ้นไป',
    description: 'ระบบเทรดโลหะเงินที่มีความแม่นยำสูงสุดในโลก พร้อมประกันเงินต้น 100%',
    userCount: 180,
    performanceSummary: 'Win Rate 88% | Daily Active: 60',
    status: 'active',
    stats: { dailyWinRate: '86%', weeklyWinRate: '87%', monthlyWinRate: '88%', globalRank: 26, totalActiveUsers: 180, dailyActiveUsers: 60, weeklyActiveUsers: 120 },
    features: ['Quantum Calculation AI', '24/7 Institutional Support'],
    reviews: [],
    supportedSymbols: ['XAGUSD', 'XAGAUD']
  }
];

export const THAI_BANKS = [
  { id: 'kbank', name: 'กสิกรไทย', color: '#138B2E', shortName: 'K-Bank' },
  { id: 'scb', name: 'ไทยพาณิชย์', color: '#4E2E7F', shortName: 'SCB' },
  { id: 'bbl', name: 'กรุงเทพ', color: '#1E4598', shortName: 'BBL' },
  { id: 'ktb', name: 'กรุงไทย', color: '#00AEEF', shortName: 'KTB' },
  { id: 'bay', name: 'กรุงศรีอยุธยา', color: '#FEC43B', shortName: 'Krungsri' },
  { id: 'ttb', name: 'ทีทีบี', color: '#002D63', shortName: 'ttb' },
  { id: 'gsb', name: 'ออมสิน', color: '#EB198D', shortName: 'GSB' },
  { id: 'baac', name: 'ธ.ก.ส.', color: '#008542', shortName: 'BAAC' },
  { id: 'uob', name: 'ยูโอบี', color: '#00366D', shortName: 'UOB' }
];
